FROM openjdk:18.0.1-slim

# install curl for a health check
RUN apt-get update && apt-get install -y curl
# for spring boot
VOLUME /tmp
COPY target/fraud-1.0-SNAPSHOT.jar fraud.jar
ENTRYPOINT ["java", "-jar", "fraud.jar"]